//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.MathService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathService1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/multiply", ReplyAction="http://tempuri.org/IService1/multiplyResponse")]
        int multiply(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/multiply", ReplyAction="http://tempuri.org/IService1/multiplyResponse")]
        System.Threading.Tasks.Task<int> multiplyAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/divide", ReplyAction="http://tempuri.org/IService1/divideResponse")]
        double divide(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/divide", ReplyAction="http://tempuri.org/IService1/divideResponse")]
        System.Threading.Tasks.Task<double> divideAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        int add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        System.Threading.Tasks.Task<int> addAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subtract", ReplyAction="http://tempuri.org/IService1/subtractResponse")]
        int subtract(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subtract", ReplyAction="http://tempuri.org/IService1/subtractResponse")]
        System.Threading.Tasks.Task<int> subtractAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkIsInt", ReplyAction="http://tempuri.org/IService1/checkIsIntResponse")]
        bool checkIsInt(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkIsInt", ReplyAction="http://tempuri.org/IService1/checkIsIntResponse")]
        System.Threading.Tasks.Task<bool> checkIsIntAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/circleArea", ReplyAction="http://tempuri.org/IService1/circleAreaResponse")]
        double circleArea(int radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/circleArea", ReplyAction="http://tempuri.org/IService1/circleAreaResponse")]
        System.Threading.Tasks.Task<double> circleAreaAsync(int radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/coneVolume", ReplyAction="http://tempuri.org/IService1/coneVolumeResponse")]
        double coneVolume(int radius, int height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/coneVolume", ReplyAction="http://tempuri.org/IService1/coneVolumeResponse")]
        System.Threading.Tasks.Task<double> coneVolumeAsync(int radius, int height);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication5.MathService1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication5.MathService1.IService1>, WebApplication5.MathService1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int multiply(int x, int y) {
            return base.Channel.multiply(x, y);
        }
        
        public System.Threading.Tasks.Task<int> multiplyAsync(int x, int y) {
            return base.Channel.multiplyAsync(x, y);
        }
        
        public double divide(int x, int y) {
            return base.Channel.divide(x, y);
        }
        
        public System.Threading.Tasks.Task<double> divideAsync(int x, int y) {
            return base.Channel.divideAsync(x, y);
        }
        
        public int add(int x, int y) {
            return base.Channel.add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int x, int y) {
            return base.Channel.addAsync(x, y);
        }
        
        public int subtract(int x, int y) {
            return base.Channel.subtract(x, y);
        }
        
        public System.Threading.Tasks.Task<int> subtractAsync(int x, int y) {
            return base.Channel.subtractAsync(x, y);
        }
        
        public bool checkIsInt(string str) {
            return base.Channel.checkIsInt(str);
        }
        
        public System.Threading.Tasks.Task<bool> checkIsIntAsync(string str) {
            return base.Channel.checkIsIntAsync(str);
        }
        
        public double circleArea(int radius) {
            return base.Channel.circleArea(radius);
        }
        
        public System.Threading.Tasks.Task<double> circleAreaAsync(int radius) {
            return base.Channel.circleAreaAsync(radius);
        }
        
        public double coneVolume(int radius, int height) {
            return base.Channel.coneVolume(radius, height);
        }
        
        public System.Threading.Tasks.Task<double> coneVolumeAsync(int radius, int height) {
            return base.Channel.coneVolumeAsync(radius, height);
        }
    }
}
